[client]
showErrorDetails = true

[theme]
#primaryColor = "white"
backgroundColor = "#EAE7DC"
secondaryBackgroundColor ="#F2F2F2"
[secrets]

# List of locations where secrets are searched. Entries can be a path to
# toml file or directory path where Kubernetes style secrets will be
# scanned. Order is important, import is first to last, so secrets in later
# files will take precedence over earlier ones.

# Default: [ <path to local environment's secrets.toml file>, <path to project's secrets.toml file>,]
files = [ "~/.streamlit/secrets.toml",]